### ISSUE TITLE
Test for setThisWithApply passes in an array to begin with, and so defeats the entire concept of .apply

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-advanced-functions-this-code-along#1]
The test is passing in it's multiple args for the third parameter as an array: args == [20, 'black'], and so you need to write your function invocation as fn.apply(thisValue, args) in order to pass the tests. 

args is an array, so the tests do not pass if you use apply properly, i.e. fn.apply(thisValue, [arg1, arg2]). This makes the correct implementation seem too much like call, simply because the test is written poorly.

**Comment by sgharms** [comment]
Hey @LaneMiller , I don't see a test directory nor do I see that there's been one in any of the recent commit history. I _do_ see:

```js
deliverFood.call(gc, 'Terry', '4');
deliverFood.apply(pbj, ['Jesse', '15']);
```

Which seems to demonstrate the difference between call and apply. Did you mean to open this on a different repo? Please open on the correct repo or let me know how you were encountering this problem. Thanks.

Steven
